// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: person.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressBookServiceClient is the client API for AddressBookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressBookServiceClient interface {
	AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Status, error)
	ListPeople(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (AddressBookService_ListPeopleClient, error)
	AddPeople(ctx context.Context, opts ...grpc.CallOption) (AddressBookService_AddPeopleClient, error)
}

type addressBookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressBookServiceClient(cc grpc.ClientConnInterface) AddressBookServiceClient {
	return &addressBookServiceClient{cc}
}

func (c *addressBookServiceClient) AddPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/tutorial.AddressBookService/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressBookServiceClient) ListPeople(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (AddressBookService_ListPeopleClient, error) {
	stream, err := c.cc.NewStream(ctx, &AddressBookService_ServiceDesc.Streams[0], "/tutorial.AddressBookService/ListPeople", opts...)
	if err != nil {
		return nil, err
	}
	x := &addressBookServiceListPeopleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AddressBookService_ListPeopleClient interface {
	Recv() (*AddressBook, error)
	grpc.ClientStream
}

type addressBookServiceListPeopleClient struct {
	grpc.ClientStream
}

func (x *addressBookServiceListPeopleClient) Recv() (*AddressBook, error) {
	m := new(AddressBook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *addressBookServiceClient) AddPeople(ctx context.Context, opts ...grpc.CallOption) (AddressBookService_AddPeopleClient, error) {
	stream, err := c.cc.NewStream(ctx, &AddressBookService_ServiceDesc.Streams[1], "/tutorial.AddressBookService/AddPeople", opts...)
	if err != nil {
		return nil, err
	}
	x := &addressBookServiceAddPeopleClient{stream}
	return x, nil
}

type AddressBookService_AddPeopleClient interface {
	Send(*Person) error
	Recv() (*Status, error)
	grpc.ClientStream
}

type addressBookServiceAddPeopleClient struct {
	grpc.ClientStream
}

func (x *addressBookServiceAddPeopleClient) Send(m *Person) error {
	return x.ClientStream.SendMsg(m)
}

func (x *addressBookServiceAddPeopleClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddressBookServiceServer is the server API for AddressBookService service.
// All implementations must embed UnimplementedAddressBookServiceServer
// for forward compatibility
type AddressBookServiceServer interface {
	AddPerson(context.Context, *Person) (*Status, error)
	ListPeople(*ListReq, AddressBookService_ListPeopleServer) error
	AddPeople(AddressBookService_AddPeopleServer) error
	mustEmbedUnimplementedAddressBookServiceServer()
}

// UnimplementedAddressBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAddressBookServiceServer struct {
}

func (UnimplementedAddressBookServiceServer) AddPerson(context.Context, *Person) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPerson not implemented")
}
func (UnimplementedAddressBookServiceServer) ListPeople(*ListReq, AddressBookService_ListPeopleServer) error {
	return status.Errorf(codes.Unimplemented, "method ListPeople not implemented")
}
func (UnimplementedAddressBookServiceServer) AddPeople(AddressBookService_AddPeopleServer) error {
	return status.Errorf(codes.Unimplemented, "method AddPeople not implemented")
}
func (UnimplementedAddressBookServiceServer) mustEmbedUnimplementedAddressBookServiceServer() {}

// UnsafeAddressBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressBookServiceServer will
// result in compilation errors.
type UnsafeAddressBookServiceServer interface {
	mustEmbedUnimplementedAddressBookServiceServer()
}

func RegisterAddressBookServiceServer(s grpc.ServiceRegistrar, srv AddressBookServiceServer) {
	s.RegisterService(&AddressBookService_ServiceDesc, srv)
}

func _AddressBookService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.AddressBookService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookServiceServer).AddPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressBookService_ListPeople_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AddressBookServiceServer).ListPeople(m, &addressBookServiceListPeopleServer{stream})
}

type AddressBookService_ListPeopleServer interface {
	Send(*AddressBook) error
	grpc.ServerStream
}

type addressBookServiceListPeopleServer struct {
	grpc.ServerStream
}

func (x *addressBookServiceListPeopleServer) Send(m *AddressBook) error {
	return x.ServerStream.SendMsg(m)
}

func _AddressBookService_AddPeople_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AddressBookServiceServer).AddPeople(&addressBookServiceAddPeopleServer{stream})
}

type AddressBookService_AddPeopleServer interface {
	Send(*Status) error
	Recv() (*Person, error)
	grpc.ServerStream
}

type addressBookServiceAddPeopleServer struct {
	grpc.ServerStream
}

func (x *addressBookServiceAddPeopleServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *addressBookServiceAddPeopleServer) Recv() (*Person, error) {
	m := new(Person)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddressBookService_ServiceDesc is the grpc.ServiceDesc for AddressBookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressBookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.AddressBookService",
	HandlerType: (*AddressBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _AddressBookService_AddPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPeople",
			Handler:       _AddressBookService_ListPeople_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddPeople",
			Handler:       _AddressBookService_AddPeople_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "person.proto",
}
